### ISSUE TITLE
NuGet integration - Docu

### ISSUE THREAD

**Issue by Tip77** [3F/vsSolutionBuildEvent#62]
Hi, 

sorry if this is the wrong place to post a question. The main page referenced the Wiki where I didn't find a link to a forum or aslike.

What I am looking for is "How to setup NuGet package so that I don't have to install the VisualStudio Extension".

Many thanks
Martin

**Comment by 3F** [comment]
Don't worry, this is a correct place to ask anything related to vsSolutionBuildEvent since *Disqus* is disabled now.

> What I am looking for is "How to setup NuGet package so that I don't have to install the VisualStudio Extension".

Unfortunately part of the documentation contains outdated information but you need to look at this:
* [https://vssbe.r-eg.net/doc/CI/CI.MSBuild/](https://vssbe.r-eg.net/doc/CI/CI.MSBuild/)  
    * *vsSolutionBuildEvent welcomes any updates that will be considered through GitHub PR.*

Please note the following changes starting with [v1.14](https://github.com/3F/vsSolutionBuildEvent/blob/master/changelog.txt):

> * CHANGED: NuGet package `vsSBE.CI.MSBuild` is obsolete. Please use new:
           https://www.nuget.org/packages/vsSolutionBuildEvent
           Also new 'tools\' folder instead of 'bin\'.

Therefore you can simply try like this: 

[`gnt`](https://github.com/3F/GetNuTool/releases/latest)` /p:ngpackages="vsSolutionBuildEvent"` 
( **old** packages still can be found here: https://www.nuget.org/packages/vsSBE.CI.MSBuild/ )

So, for example, [Conari](https://github.com/3F/Conari) used this bootstrap to activate modern vsSolutionBuildEvent:

* https://github.com/3F/Conari/blob/b861e08a2e103d3b4288d7dc20c2c95cc3f8f85d/build.bat

Here is result for CI (without VisualStudio Extension): https://ci.appveyor.com/project/3Fs/conari-wkygr/builds/30509246

**Comment by Tip77** [comment]
Thanks for the quick response. I manually installed the NuGet packages (via VisualStudio). How do I now setup the VisualStudio solution so that the script in .vssbe is executed?

**Comment by 3F** [comment]
> I manually installed the NuGet packages (via VisualStudio).

Please be careful, this is not supported at least officially because of https://github.com/NuGet/Home/issues/1521  (we do not follow any possible nuget solution for this, so I can't guarantee anything)

I recommend https://github.com/3F/GetNuTool

> How do I now setup the VisualStudio solution so that the script in .vssbe is executed?

You don't need to do anything. Initially you need just to:

1. Choose the way of receiving NuGet package that supports *solution level*. Any ways. I recommend GetNuTool because it can be even integrated into batch scripts and does not require any dependencies.
2. Just activate plugin as you're prefer ([doc](https://vssbe.r-eg.net/doc/CI/CI.MSBuild/#how-to-use))

That's all.

Modern versions provides cim.cmd wrapper (located in packages\vsSolutionBuildEvent\cim.cmd by default)

I hope you understand that for interaction with vsSolutionBuildEvent inside IDE you need of course VisualStudio plugin. For other cases you can simply activate it such from my example above:

```bat
packages\vsSolutionBuildEvent\cim.cmd "YourSolutionFile.sln"
```

**Comment by 3F** [comment]
(not tested) More like it could be probably also activated even without VisualStudio plugin through *project Properties* - *Build Events* or manually via msbuild:

```xml
  <Target Name="ActivateVSSBE" BeforeTargets="Build"> 
    <!-- or better to try with BeforeBuild or _CheckForInvalidConfigurationAndPlatform or AssignProjectConfiguration or _PrepareForBuild etc -->
    <Exec Command="packages\vsSolutionBuildEvent\cim.cmd $(SolutionPath)" WorkingDirectory="$(SolutionDir)" />
  </Target>
```

that's obviously strange, but if you need, you can try this

**Comment by Tip77** [comment]
My intention was to include versioning without forcing everyone to install the VisualStudio plug-in. That makes onboarding easier.

**Comment by 3F** [comment]
> My intention was to include versioning without forcing everyone to install the VisualStudio plug-in. 

You do **not** need forcing everyone to install the any plugin or some package.
Because all this will work without it. For any build. And I already gave you link to CI above to prove it.
