### ISSUE TITLE
MSBuild Properties not changing according to solution configuration

### ISSUE THREAD

**Issue by DrGierth** [3F/vsSolutionBuildEvent#71]
Hello,

**this Script:**
![grafik](https://user-images.githubusercontent.com/12048733/99837019-396cf580-2b67-11eb-9c03-b16d8c7e831f.png)

**was original written when VS IDE Solution Configuration was set to "Debug", and it worked as it should.**

**After switching the VS IDE Solution Configuration to "Release" the output is still going to the debug folders.
Checking the MSBuild Properties in vsSBE shows debug setting:**

![grafik](https://user-images.githubusercontent.com/12048733/99836609-a764ed00-2b66-11eb-8aef-dd951ae8cb8e.png)

**Checking VS IDE Macros gives the expected setting:**

![grafik](https://user-images.githubusercontent.com/12048733/99836864-0165b280-2b67-11eb-8494-650421f851c2.png)

[Output-BuildOrder.txt](https://github.com/3F/vsSolutionBuildEvent/files/5575522/Output-BuildOrder.txt)
[Output-vsSolutionBuildEvent.txt](https://github.com/3F/vsSolutionBuildEvent/files/5575525/Output-vsSolutionBuildEvent.txt)

Is my vsSBE configuration wrong or do we have an issue?

Thank you in advance for your efforts.

Michael

**Comment by 3F** [comment]
Confirmed. Thanks for the report!

Seems like this affects only EnvDTE environment (VS IDE)

**Temporarily** you can either use CI environment https://www.nuget.org/packages/vsSolutionBuildEvent
or some conditions around `$(Configuration)` since it will be resolved correctly for both environments. 

```java
#[( $(Configuration) == "Release" )
{
    ...
}
else{  ...  }]
```

Unfortunately no ETA https://twitter.com/GitHub3F/status/1320425255291265026
